services:
  crosswatch:
    image: ghcr.io/cenodude/crosswatch:latest
    container_name: crosswatch
    ports:
      - "${CROSSWATCH_PORT:-8787}:8787"
    environment:
      TZ: "${TZ:-Europe/Amsterdam}"
    volumes:
      - crosswatch_config:/config
    restart: unless-stopped

volumes:
  crosswatch_config: